### PR TITLE
update repository layout

### PR DESCRIPTION
**Pull request by arnetheduck**
Make repository layout match https://github.com/eth-clients/mainnet:

* remove `deploy_block.txt` (duplicate of `deposit_contract_block.txt`)
* remove `boot_enr.txt` (duplicate of `bootstrap_nodes.txt`)
* `parsedBeaconState.json` -> `genesis.json`
* `bepolia` -> `metadata`

### CODE REVIEW

**Comment by barnabasbusa** [comment]
Could you please adjust the PR to revert the change from parsedBeaconState to leave it as is? (as also discussed on discord).

**Comment by arnetheduck** [comment]
> Could you please adjust the PR to revert the change from parsedBeaconState to leave it as is

thoughts on separate folders for el and cl? then each world can have its own names and formats

**Comment by barnabasbusa** [comment]
I'd be against it. We could rename it to literally anything else but genesis.json.

**Comment by arnetheduck** [comment]
hm, in that case, I think it might be best to move it out of here altogether - ie the mainnet/holesky repos don't have it - I think it's mostly for informational purposes / easy grepping - might as well move it down one level since it's not part of official "metadata" - then there's no confusion as to what files *must* be here to launch a network

**Comment by barnabasbusa** [comment]
holesky doesn't have it because it would be like 2GB. Mainnet could have it.

**Comment by arnetheduck** [comment]
> holesky doesn't have it because it would be like 2GB. Mainnet could have it.

yes - the point is more that clients don't need the parsed version to start - the intent is for `metadata` to hold all information necessary but nothing else, so that it's unambiguous to implement - otherwise, we might get into silly out-of-sync issues between the two files, which is where this whole game started

**Comment by arnetheduck** [comment]
ae686ecd37983057d1ec63fb4f2a3374ba62a493 is the suggestion, concretely

**Review by barnabasbusa — APPROVED** [review]

**Pull request merged**
